markup:
  first_comment_is_literal: true
format:
  line_width: 100
parse:
  additional_commands:
    cxx_flags_by_compiler_frontend:
      pargs: 0
      kwargs:
        OUTPUT: 1
        GNU: '*'
        MSVC: '*'
        FILTER: 0
    modernize_target_link_libraries:
      pargs: 1
      kwargs:
        SCOPE: 1
        TARGETS: '*'
        LIBRARIES: '*'
        INCLUDE_DIRS: '*'
    pinocchio_target:
      pargs: 1
      kwargs:
        INTERFACE: 0
        SCALAR: 1
        LIBRARY_PUBLIC_SCOPE: 1
        SOURCES: '*'
    add_pinocchio_cpp_example:
      pargs: 1
      kwargs:
        PARSERS: 0
        CPPAD: 0
        CPPADCG: 0
        CASADI: 0
    add_pinocchio_unit_test:
      pargs: 1
      kwargs:
        HEADER_ONLY: 0
        PARSERS: 0
        EXTRA: 0
        COLLISION: 0
        PARALLEL: 0
        PARSERS_OPTIONAL: 0
        EXTRA_OPTIONAL: 0
        COLLISION_OPTIONAL: 0
        PARALLEL_OPTIONAL: 0
        PACKAGES: '*'
    install_python_files:
      pargs: 0
      kwargs:
        MODULE: 1
        FILES: '*'
    add_project_dependency:
      pargs: '*'
      kwargs:
        PKG_CONFIG_REQUIRES: 1
        FOR_COMPONENT: 1
        FIND_EXTERNAL: 1
