ci:
  autoupdate_schedule: quarterly
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.9
  hooks:
  - id: ruff
    args:
    - --fix
  - id: ruff-format
- repo: https://github.com/BlankSpruce/gersemi
  rev: 0.15.1
  hooks:
  - id: gersemi
    exclude: |
      (?x)^(
          .*\.(h|hh|pc|py)\.cmake|
          cython/python/FindPython.*\.cmake|
          boost/FindBoost\.cmake|
          python/FindPython.*\.cmake|
          GNUInstallDirs\.cmake
      )$
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v19.1.1
  hooks:
  - id: clang-format
    args:
    - --style=Google
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-added-large-files
  - id: check-ast
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: check-yaml
  - id: debug-statements
  - id: destroyed-symlinks
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: fix-byte-order-marker
  - id: mixed-line-ending
  - id: trailing-whitespace
- repo: meta
  hooks:
  - id: check-hooks-apply
  - id: check-useless-excludes
exclude: \.js$
